name: P4
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5259741272311658
title: Personal and Corporate Mastery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005f8f'
    - '#d5cdcb'
    - '#6aa2b9'
    - '#4d4141'
    - '#011732'
  brandStrength: 1
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
