name: P4
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5259741272311658
title: Personal and Corporate Mastery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#1c5424'
    - '#7ec04b'
    - '#58915f'
    - '#91db49'
  brandStrength: 0
  lightness: 0.9622147029731423
  saturation: 0.40317307133227587
  rhythmicContrast: 0.352118510985747
purpose: []
