name: P4
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5259741272311658
title: Personal and Corporate Mastery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f9cd4'
    - '#015385'
    - '#91cff4'
    - '#ba6d1a'
    - '#c69f97'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 0.352118510985747
purpose: []
